gh actions: add more checks
Signed-off-by: Jonas Remmert <jremmert@gmx.net>

diff --git a/.github/workflows/compliance.yml b/.github/workflows/compliance.yml
--- a/.github/workflows/compliance.yml
+++ b/.github/workflows/compliance.yml
@@ -1,38 +1,68 @@
-name: Build Sphinx Doc
+name: Compliance Checks
 
-on:
-  pull_request:
+on: pull_request
 
 jobs:
-  build-doc:
+  check_compliance:
     runs-on: ubuntu-latest
     steps:
-
-    - name: Checkout
-      uses: actions/checkout@v4
-
-    - name: Install Packages
+    - name: Update PATH for west
       run: |
-        sudo apt-get update
-        sudo apt-get install plantuml tox python3-pip -y
+        echo "$HOME/.local/bin" >> $GITHUB_PATH
 
-    - name: Build static site with Tox
-      run: |
-        cd doc
-        tox -e py3-html
-
-    - name: Deploy Preview
-      uses: peaceiris/actions-gh-pages@v4
+    - name: Checkout the code
+      uses: actions/checkout@v2
       with:
-        github_token: ${{ secrets.GITHUB_TOKEN }}
-        publish_dir: doc/build/html
-        destination_dir: 'previews/${{ github.event.number }}'
+        ref: ${{ github.event.pull_request.head.sha }}
+        fetch-depth: 0
 
-    - name: Create status check with preview link
+    - name: cache-pip
+      uses: actions/cache@v1
+      with:
+        path: ~/.cache/pip
+        key: ${{ runner.os }}-doc-pip
+
+    - name: Install python dependencies
       run: |
-        PREVIEW_URL="https://flownexus-lwm2m.github.io/waterlevel_monitor/previews/${{ github.event.number }}"
-        PAYLOAD=$(echo '{}' | jq --arg name 'Documentation Preview' --arg url "${PREVIEW_URL}" '{"name": $name, "head_sha": "${{ github.event.pull_request.head.sha }}", "details_url": $url, "status": "completed", "conclusion": "success", "output": {"title": $name, "summary": "Preview available at", "text": $url}}')
-        curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
-             -H "Content-Type: application/json" \
-             -X POST -d "${PAYLOAD}" \
-             "https://api.github.com/repos/${{ github.repository }}/check-runs"
+        pip3 install setuptools
+        pip3 install wheel
+        pip3 install python-magic junitparser gitlint pylint pykwalify
+
+    - name: Run Compliance Tests
+      continue-on-error: true
+      id: compliance
+      env:
+        BASE_REF: ${{ github.base_ref }}
+      run: |
+        # debug
+        ls -la
+        git log  --pretty=oneline | head -n 10
+        ./ci/check_compliance.py -m checkpatch -m Gitlint -c origin/${BASE_REF}..
+
+    - name: upload-results
+      uses: actions/upload-artifact@v3
+      continue-on-error: True
+      with:
+        name: compliance.xml
+        path: compliance.xml
+
+    - name: check-warns
+      run: |
+        if [[ ! -s "compliance.xml" ]]; then
+          exit 1;
+        fi
+
+        for file in Nits.txt checkpatch.txt Identity.txt Gitlint.txt pylint.txt Devicetree.txt Kconfig.txt; do
+          if [[ -s $file ]]; then
+            errors=$(cat $file)
+            errors="${errors//'%'/'%25'}"
+            errors="${errors//$'\n'/'%0A'}"
+            errors="${errors//$'\r'/'%0D'}"
+            echo "::error file=${file}::$errors"
+            exit=1
+          fi
+        done
+
+        if [ "${exit}" == "1" ]; then
+          exit 1;
+        fi
